name: Build and push to ECR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check required secrets
        env:
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          test -n "$AWS_ROLE_ARN" || { echo "Missing secret: AWS_ROLE_ARN"; exit 1; }
          test -n "$AWS_REGION" || { echo "Missing secret: AWS_REGION"; exit 1; }
          test -n "$ECR_REPOSITORY" || { echo "Missing secret: ECR_REPOSITORY"; exit 1; }

      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Verify ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names "$ECR_REPOSITORY" --region "$AWS_REGION" >/dev/null || {
            echo "ECR repository $ECR_REPOSITORY not found in $AWS_REGION"; exit 1;
          }

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        run: |
          IMAGE_URI="${{ steps.ecr.outputs.registry }}/${ECR_REPOSITORY}"
          TAG_SHA="${{ github.sha }}"
          docker buildx build \
            --platform linux/amd64 \
            -t "${IMAGE_URI}:${TAG_SHA}" \
            -t "${IMAGE_URI}:latest" \
            --push .
