name: Build and push to ECR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check required secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          test -n "$AWS_ACCESS_KEY_ID" || { echo "Missing secret: AWS_ACCESS_KEY_ID"; exit 1; }
          test -n "$AWS_SECRET_ACCESS_KEY" || { echo "Missing secret: AWS_SECRET_ACCESS_KEY"; exit 1; }
          test -n "$AWS_REGION" || { echo "Missing secret: AWS_REGION"; exit 1; }
          test -n "$ECR_REPOSITORY" || { echo "Missing secret: ECR_REPOSITORY"; exit 1; }

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        env:
          IMAGE_REGISTRY: ${{ steps.ecr.outputs.registry }}
          IMAGE_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI="$IMAGE_REGISTRY/$IMAGE_REPOSITORY"
          docker build \
            -t "$IMAGE_URI:$IMAGE_TAG" \
            -t "$IMAGE_URI:latest" \
            .
          docker push "$IMAGE_URI:$IMAGE_TAG"
          docker push "$IMAGE_URI:latest"
